server:
  port: 9870

spring:
  application:
    name: quickinit
  profiles:
    active: dev

mybatis-plus:
  typeAliasesPackage: top.amfun.quickinit.entity
  mapper-locations: classpath:top/amfun/quickinit/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: quickinit-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

logging:
  config: classpath:log4j2.xml

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /v3/api-docs/**
      - /**/*.js
      - /**/*.css
      - /**/*.html
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /user/login
      - /user/register
      - /user/info
      - /user/logout
